language: node_js
node_js:
  - "0.10"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install --yes openssh-server
  - ssh-keygen -t rsa -f ~/.ssh/id_dsa -N ''
  - ls -al ~/.ssh/
  - ssh-copy-id travis@localhost
  - chmod 600 ~/.ssh/authorized_keys
  - ssh localhost
