language: node_js
node_js:
  - "0.10"
before_script:
  - node travis/install-openssh-server.js
  - cat /etc/ssh/sshd_config
  - ssh-keygen -t dsa
  - ssh-copy-id username@remotehost
  - chmod 600 .ssh/authorized_keys
version: 00